<a href="https://colab.research.google.com/github/psourabh094/Email-spam-dedection/blob/main/email_spam_or_ham_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import all importent libarary
import numpy as np
import pandas as pd
import nltk 
from nltk.corpus import stopwords
import string

In [2]:
#Load the data 
from google.colab import files
uploadede = files.upload()

Saving spam.csv to spam.csv


In [3]:
#read loaded data
df=pd.read_csv('spam.csv')

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
#checking shape of data 
df.shape

(5572, 2)

In [7]:
#checking null values
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [8]:
#cheking duplicates
df.duplicated().sum()

415

In [11]:
#drop the duplicates
df_update=df.drop_duplicates(keep='first')

In [12]:
#checking shape after droping duplicates
df_update.shape

(5157, 2)

In [26]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()


In [27]:
#lable encoding
df['Category'] = encoder.fit_transform(df['Category'])

In [28]:
#download the nltk stopwords packegs
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [29]:
def process_text(text):

  #1 remove punuctation
  #2 remove stopwords
  #3 returen a list after clean texts

  #1 remove punuctation
  no_punc=[char for char in text if char not in string.punctuation]
  no_punc=''.join(no_punc)

  #2 remove stopwords
  clean_words=[word for word in no_punc.split() if word.lower() not in stopwords.words('english')]

  #returen a list after clean texts
  return clean_words



In [30]:
from IPython.utils import process
df['Message'].head().apply(process_text)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: Message, dtype: object

In [31]:
#convert a collecton of text to matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
masseges_bow = CountVectorizer(analyzer=process_text).fit_transform(df['Message'])

In [32]:
#spliting the data into test and training data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(masseges_bow,df['Category'], test_size = 0.20,random_state = 0)


In [33]:
#get the shape of data 
masseges_bow.shape

(5572, 11422)

In [34]:
#creating a naive bayes classifier model
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

In [35]:
#print the pridictions
print(classifier.predict(X_train))

#print the actulae values
print(y_train.values)

[0 0 0 ... 1 0 0]
[0 0 0 ... 1 0 0]


In [44]:
#Evaluate the model on training data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train, pred))



              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3870
           1       0.98      0.97      0.98       587

    accuracy                           0.99      4457
   macro avg       0.99      0.99      0.99      4457
weighted avg       0.99      0.99      0.99      4457



In [45]:
print(accuracy_score(y_train, pred))

0.9943908458604442


In [37]:
#print the pridictions
print(classifier.predict(X_test))

#print the actulae values
print(y_test.values)

[0 1 0 ... 0 0 0]
[0 1 0 ... 0 1 0]


In [47]:
#Evaluate the model on testing data
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test, pred))
print()

              precision    recall  f1-score   support

           0       0.99      0.96      0.98       955
           1       0.81      0.94      0.87       160

    accuracy                           0.96      1115
   macro avg       0.90      0.95      0.92      1115
weighted avg       0.96      0.96      0.96      1115




In [48]:
print(accuracy_score(y_test, pred))

0.9596412556053812
